---
output: github_document
---

### Washout period

-   ~~Washout start date: 182 days prior to the first MSK diagnosis~~

-   ~~Washout end date: date of the first MSK diagnosis~~

### Exclusion

1.  ~~Exclude all individuals without a minimum of 9 months of continuous enrollment. They must be continuously enrolled 6 months prior to the first MSK diagnosis and 3 months after that diagnosis~~
2.  In the washout period:
    1.  ~~any opioid prescription~~
    2.  any OUD diagnosis (using the expansive definition)
3.  Ineligible state (limit to expansion states, excluding MD)
4.  Dual eligible
5.  Pregnant
6.  Outside of age range 19-65
7.  Cancer, long-term care, palliative care, institutionalized

### Inclusion

1.  ~~Individuals prescribed an opioid for pain in the period from the first MSK diagnosis to 3-months in the future [SRVC_BGN_DT, SRVC_BGN_DT + 91]. Call this the **exposure period.**~~

### Exposures

In the exposure period, define 2 variables: A1, A2

-   ~~A1: MME (max)~~

-   ~~A2: days supply (max)~~

Truncate these variables to limit outliers.

In addition, define 3 subsets:

1.  ~~B1 = A1 ≥ 50 MME~~
2.  ~~B2 = A2 \> 7 days~~
3.  ~~B3 = A1 ≥ 50 MME ∩ A2 \> 7 days~~

### Outcomes

Discretise follow up time in to 5, 3 month intervals for a total of 15 months of follow up (starting after the exposure period?). At each point make a censoring variable and OUD variable.Individuals are censored when:

1)  they turn 65

2)  they become dual eligible

3)  on December 31, 2019

4)  after 15 months of follow up
